config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => "homes#about"
  root 'homes#top'
  devise_for :users
  resources :users
  resources :books

  resources :post_images, only: [:new, :create, :index, :show] do
    resources :post_comments, only: [:create, :destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
    validates :body, presence: true, length: { maximum: 50 }
    has_many :post_comments, dependent: :destroy
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
  belongs_to :post_image
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  has_many :post_comments, dependent: :destroy

 
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?

  def after_sign_in_path_for(resource)
  	user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
  	root_path
  end

  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!
	
	def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book, notice: "successfully"
    else
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: "successfully"
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
  end


  def destroy
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
  end
end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "successfully"
    else
      render :edit
    end
  end

  private
    def user_params
       params.require(:user).permit(:name, :introduction, :profile_image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12' %>
  </div>

  <div class="field row">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'col-xs-12 book_body'%>
  </div>

  <div class="actions row">
    <%= f.submit "Update Book", class: 'btn btn-primary col-xs-12'%>
  </div>

<% end %>
<%= link_to 'Show', @book %>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
<!-----------------User Info------------------------------------->
     <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr> 

        <th>name</th>
        <th><%= current_user.name %></th>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
    </table>
<!-----------------User Info------------------------------------->
<!-----------------new book------------------------------------->
<h1>New book</h1>

<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %>

<br><%= f.submit "Create Book" %></br>

<% end %>
</div>
<!-----------------new book------------------------------------->
<div class="col-xs-9">
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<% if flash[:notice] %>
				<div class="flash">
					<%= flash[:notice] %>
				</div>
			<% end %>
			   <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr> 

        <tr>
        <th>name</th>
       <th><%= @book.user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
       <th><%= @book.user.introduction %></th>
      </tr>
    </table>

			<h1>New book</h1>

       <%= form_for(@book) do |f| %>
        <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  </div>
  <% end %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %>

<%= f.submit "Create Book" %> 

<% end %>
</div>
   <div class="col-xs-9">
		<h1>Book detail</h1>

		<table class="table">
			<tr>
				<td><%= link_to user_path(@book.user.id) do %><%= attachment_image_tag @book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %><br><%= @book.user.name %><% end %></td>
				<td><%= link_to @book.title, book_path(@book.id) %></td>
				<td><%= @book.body %></td>
				<% if @book.user.id == current_user.id %>
				<td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
				<td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" %>
				<% end %>
				</td>
			</tr>
		</table>
		</div>
	</div>
</div>

<li>
  <i class="fa fa-comment"></i>
  <a href="#comments"><%= @book.user.post_comments.count %></a>
</li>

:
:

<div class="comment-list bt style-2" id="comments">
  <div class="float-wrapper">
    <h2 class="comment-count"><%= @book.user.post_comments.count %>件コメント</h2>
  </div>

app/views/homes/about.html.erb
  	<div class='body'>
      <div class='container'>

        <p id="notice"></p>


      	<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>


      </div>
    </div>


 

app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
          <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><%= link_to 'Log in',new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error.html.erb
<% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookersnew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home',user_path(current_user),class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users',users_path,class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Books',books_path ,class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path,class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About',home_about_path,class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'glyphicon glyphicon-log-in sign_in' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

    <%= yield %>
    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
      <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr> 
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
    </table>
    <div class='row'>
      <%= link_to '',edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench user_edit_#{user.id}" %>
    </div>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= render 'layouts/error', user:@user %>

<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "user_name" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
  </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "introduction" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
<!-----------------User Info------------------------------------->
     <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr> 

        <tr>
        <th>name</th>
       <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
       <th><%= @user.introduction %></th>
      </tr>
      <%= link_to 'edit',edit_user_path(@user) %>
    </table>
<!-----------------User Info------------------------------------->
<!-----------------new book------------------------------------->
<h1>New book</h1>

<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %>

<br><%= f.submit "Create Book" %></br>

<% end %>
</div>
<!-----------------new book------------------------------------->
<!----- 質問　------->
<div class="col-xs-9">
    <h2>Users</h2>

    <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <% @users.each do |user| %>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
      <% end %>
  </tbody>
</table>

  </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>
<!-----------------User Info------------------------------------->
     <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr> 

        <tr>
        <th>name</th>
       <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
       <th><%= @user.introduction %></th>
      </tr>
      <%= link_to 'edit',edit_user_path(@user) %>
   </table>
<!-----------------User Info------------------------------------->
<!-----------------new book------------------------------------->
<h1>New book</h1>

<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %>

<br><%= f.submit "Create Book" %></br>

<% end %>
</div>
<!-----------------new book------------------------------------->
<div class="col-xs-9">
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>